### ISSUE TITLE
Activation not working (had it working but then rebuilt the docker)

### ISSUE THREAD

**Issue by NonaSuomy** [kercre123/wire-pod#201]
Once you hit activation what does it do at that point?

The wire-pod server can ping vectors IP ok and from a laptop on the same network can ping both vector and the server. I have dnsmasq telling everything connecting to that network that escapepod.local IP is what it's IP is. If I ping escapepod.local I get the right IP back. Yet Vector doesn't seem to see it still and the activation fails.

I had this working before with the same setup.

I wish the activation website just let you plug in the server IP

dockerfile
```sh
FROM ubuntu:latest

# Edit your timezone here:
ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update \
 && apt-get install -y sudo

RUN adduser --disabled-password --gecos '' wirepod
RUN adduser wirepod sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER wirepod

RUN sudo apt-get update && sudo apt-get install -y git
RUN sudo mkdir /wire-pod
RUN sudo chown -R wirepod:wirepod /wire-pod

RUN cd /wire-pod
RUN git clone https://github.com/kercre123/wire-pod/ wire-pod

WORKDIR /wire-pod

RUN sudo STT=vosk /wire-pod/setup.sh

RUN sudo sed -i '/#enable-dbus=yes/s/^#//g' /etc/avahi/avahi-daemon.conf
RUN sudo sed -i '/^enable-dbus/s/yes/no/' /etc/avahi/avahi-daemon.conf
RUN sudo service avahi-daemon start

WORKDIR /wire-pod/chipper

CMD sudo /wire-pod/chipper/start.sh
```
sudo docker build -t wire-pod .

```yaml
# Wire-Pod Container for Docker
# https://github.com/kercre123/wire-pod/wiki/Installation
version: "3.9"
services:
  wirepod:
    container_name: "wirepod"
    image: "wire-pod:latest"
    #labels:
    #  - "com.centurylinklabs.watchtower.enable=true"
    #  - "com.centurylinklabs.watchtower.monitor-only=false"
    volumes:
      - /var/lib/libvirt/images/usb001/docker-storage/wirepod/data:/data
    # - /run/dbus:/run/dbus:ro # This should technically get dbus running for Avahi but didn't seem to work for me.
                                                # May have to use dbus-broker instead of dbus-daemon.
    mac_address: "9e:de:ad:be:ef:42"
    hostname: escapepod
    #networks:
    #  - dhcp
    ports:
      - 80:80
      - 8080:8080
      - 443:433
      - 8084:8084
      - 5353:5353/udp
    restart: "no" # Turn this to unless-stopped if you think everything is ok 
                        # If you use docker-net-dhcp like me keep this set to no so your dockerd doesn't hang on boot. 
#networks:
#  dhcp:
#    name: "dbrv42"
#    external: true
```

docker compose up -d

Is there a way to manually activate him through the console with maybe the sdk functions instead of automagically trying to find escapepod.local could you specify the IP of the wirepod service in there someplace? 

Saw this in the logs command
10-06 03:09:02.959 info logwrapper 2075 2075 vic-cloud: Token queue error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup escapepod.local: no such host"
10-06 03:09:02.959 info logwrapper 2075 2075 vic-cloud: Error handling token request: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup escapepod.local: no such host"

So even though everything else on his network can see the server ok only he can't.

I was having this issue the first time I set it up and the only thing I did to get it going was to disable dbus in the avahi config then boom it activated last time. Not sure why it didn't work this time.
